sonar.projectKey=qrbook-node
sonar.projectName=Proyecto Final Node
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=node_modules/**

sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000
sonar.login=sqp_3d4d0c9bb7a812ffb3738b3561d97055399a5d03
