name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
<<<<<<< HEAD
=======

>>>>>>> 769febe40fb6bafce3cfd89bdd7bb86a8e8023ba
    steps:
      - uses: actions/checkout@v4

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
<<<<<<< HEAD
=======

>>>>>>> 769febe40fb6bafce3cfd89bdd7bb86a8e8023ba
